config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'homes#top'
  get 'home/about', to: 'homes#about'
  get 'book_articles', to: 'book_articles#indexall',as: 'every_articles'

  resources :users, only: [:index, :show, :edit, :update]
  get 'users/:id/userbooks', to: 'users#userbooks',as: 'show_userbooks'
  get 'users/:id/userbooksselect', to: 'users#userbookscreate',as: 'select_userbooks'

  resources :books do
    resources :book_articles
    resources :book_images
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  has_many :book_articles, dependent: :destroy
  has_many :book_images, dependent: :destroy

  attachment :book_image

  validates :title, presence: true

end

app/models/book_article.rb
class BookArticle < ApplicationRecord
  belongs_to :user
  belongs_to :book
  attachment :article_image
end

app/models/book_image.rb
class BookImage < ApplicationRecord

  attachment :book_image_main
  attachment :book_image_sub1
  attachment :book_image_sub2
  attachment :book_image_sub3

  belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image

  has_many :books, dependent: :destroy
  has_many :book_articles, dependent: :destroy

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about, :index, :show, :userbooks, :indexall] # top, about の2つのアクションのみ、ログイン無しでもアクセス可能にする
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    show_userbooks_path(current_user) # ログインした直後は、ユーザーの詳細ページに遷移
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/book_articles_controller.rb
class BookArticlesController < ApplicationController

  before_action :correct_user, only: [:edit, :update, :destroy]

  def new
    @bar = BookArticle.new
    @user = current_user
    @user_books = @user.books.all
    @book = Book.find(params[:book_id])
  end

  def create
    @bar = BookArticle.new(bar_params)
    @bar.user_id = current_user.id

    if @bar.save
      flash[:notice] = "You have created book articles successfully."
      redirect_to book_book_article_path(@bar.book_id, @bar.id)
    else
      render :new
    end
  end

  def index
    # パラメータからbook_idを取得します（例: /bars?book_id=1 の場合）
    nowbook_id = params[:book_id]

    # パラメータから取得したbook_idに合致するBookArticleを全て取得して、@barに格納します
    @bars = BookArticle.where(book_id:nowbook_id)
  end

  def indexall
    @bars = BookArticle.all
  end


  def show
    @bar = BookArticle.find(params[:id])
    @user = @bar.user
  end

  def edit
    @bar = BookArticle.find(params[:id])
    @user = current_user
    @user_books = @user.books.all
    @book = Book.find(params[:book_id])
  end

  def update
    @bar = BookArticle.find(params[:id])

    if @bar.update(bar_params)
      flash[:notice] = "You have updated article successfully."
      redirect_to book_book_article_path(@bar.book_id, @bar.id)
    else
      render :edit
    end
  end


  def destroy
    bar = BookArticle.find(params[:id])

    if bar.destroy
      flash[:notice] ="You have destroyed article successfully."
      redirect_to show_userbooks_path(current_user.id)
    end
  end


  private
  # ストロングパラメータ
    def bar_params
      params.require(:book_article).permit(:title, :body, :page, :chapter, :section, :book_id, :user_id, :article_image, :created_at, :updated_at)
    end

# https://qiita.com/nao0725/items/47606b8975603a12fd5e
    def correct_user
      @bar = BookArticle.find(params[:id])
      @user = @bar.user
      redirect_to book_book_articles_path unless @user == current_user
    end
end

app/controllers/book_images_controller.rb
class BookImagesController < ApplicationController
  before_action :set_book

def new
  @bookimage= BookImage.new
end

def create
  @bookimage = BookImage.new(bookimage_params)
  @bookimage.book = @book

  if @bookimage.save
    flash[:notice] = "You have created book successfully."
    redirect_to book_path(@bookimage.book)

  else
    render books_path
    # render template: "users/show"

  end
end

  def edit
  end

  def update
  end

  def destroy
  end

  private
  # ストロングパラメータ
    def bookimage_params
      params.require(:book_image).permit(:book_image_main,:book_image_sub1, :book_image_sub2, :book_image_sub3)
    end

    def set_book
      @book=Book.find(params[:book_id])
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  # 参照サイト：https://qiita.com/nao0725/items/47606b8975603a12fd5e
  before_action :correct_user, only: [:edit, :update, :destroy]

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id

    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      render :new
    end
  end

  def index
    @books = Book.all
    @user = current_user
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])

    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])

    if book.destroy
      flash[:notice] ="You have destroyed book successfully."
      redirect_to books_path
    end
  end

  # usersコントローラーのshowアクションへリダイレクトする場合
  # def destroy
  #   @book = Book.find(params[:id])  # データ（レコード）を1件取得
  #   delete_user_id = @book.user_id
  #   if @book.destroy
  #     flash[:notice] ="Book was successfully destroyed."
  #     redirect_to user_path(delete_user_id)
  #   end
  # end

  private
  # ストロングパラメータ
    def book_params
      params.require(:book).permit(:title, :author, :isbn, :book_image, :body, :created_at, :updated_at)
    end

# https://qiita.com/nao0725/items/47606b8975603a12fd5e
    def correct_user
      @book = Book.find(params[:id])
      @user = @book.user
      redirect_to books_path unless @user == current_user
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # 参照サイト：https://qiita.com/nao0725/items/47606b8975603a12fd5e
before_action :correct_user, only: [:edit]


  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def userbooks
    @user = User.find(params[:id])
    @user_books = @user.books.all
  end
  
  def userbookscreate
    @user = User.find(params[:id])
    @user_books = @user.books.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    # 現場ではこういう書き方はあまりしない
    true_or_false = @user.update(user_params)
    # if @user.update(user_params)
    if true_or_false
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name,  :introduction, :profile_image)
  end

# https://qiita.com/nao0725/items/47606b8975603a12fd5e
  def correct_user
    @user = User.find(params[:id])
    redirect_to user_path(current_user) unless @user == current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title
    title = "MathBook" #これがサイトのブランド名
    title = @page_title + " | " + title if @page_title
    title
  end
end

app/helpers/book_articles_helper.rb
module BookArticlesHelper
end

app/helpers/book_images_helper.rb
module BookImagesHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_articles/edit.html.erb
<!--Bootstrap部分  -->
<div class="container">
 <div class="row">
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

  <% if @bar.errors.any? %>
    <div id="error_explanation">
      <h2><%= @bar.errors.count %>errors prohibited this book from being saved:</h2>
      <ul>
      <% @bar.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h1>Editing Book Article</h1>

  <%= form_with(model:[@book, @bar], local: true) do |f| %>
    <div class="form-group">
      <%=f.label :book_id,"Book Title"%></br>
      <%= f.collection_select :book_id, @user_books, :id, :title, class:"form-control"%>
    </div>

    <div class="form-group">
      <%=f.label :page,"Page"%>
      <%= f.number_field :page,class:"form-control"%>
    </div>

    <div class="form-group">
      <%=f.label :chapter,"Chapter"%>
      <%= f.number_field :chapter,class:"form-control"%>
    </div>

    <div class="form-group">
      <%=f.label :section,"Section"%>
      <%= f.number_field :section,class:"form-control"%>
    </div>

    <div class="form-group">
      <%=f.label :title,"Question"%>
      <%= f.text_field :title,class:"form-control" %>
    </div>

    <div class="form-group">
      <%=f.label :body,"Explanation"%>
      <%= f.text_field :body,class:"form-control"%>
    </div>

    <div class="form-group">
      <%=f.label :article_image,"Image"%>
      <%= f.attachment_field :article_image, class:"form-control-file", id:"inputImage" %>
    </div>

    <div class="form-group">
      <%= f.submit 'Update Book',class: "btn btn-success" %>
    </div>
  <% end %>

  <%= link_to 'Show', book_book_article_path(@bar.book_id, @bar.id) %>
  <%= " | "%>
  <%= link_to "Back Index", book_book_articles_path %>

<!--Bootstrap部分  -->
  </div>
 </div>
</div>

app/views/book_articles/index.html.erb
<!--全体-->
<main>
<div class='container px-5 px-sm-0'>
  <div class='row'>

<!--ユーザーが投稿したbookのリスト-->
<div class='col-md-8 offset-md-1'>
  <h2>Books</h2>
  <table class='table table-hover table-inverse'>
    <thead>
      <tr>
        <th>User</th>
        <th>Title</th>
        <th>Autor</th>
        <th>ISBN</th>
        <th>Body</th>
      </tr>
    </thead>

<!--usersコントローラーのshowアクションで定義した@user_booksインスタンスからデータをよびだし -->
<!--booksコントローラーのindexアクションで定義した@booksインスタンスからデータをよびだし -->
    <% @books.each do |book| %>
    <tbody>
      <tr>
        <td class="text-break">
          <%= link_to user_path(book.user_id) do %>
              <%= attachment_image_tag book.user, :profile_image, :fit, 100, 100, fallback: "default-image.jpg" %>
              <br/>
              <%= book.user.name %>
          <% end %>
        </td>
        <td class="text-break">
          <%= link_to book_path(book) do %>
              <%= attachment_image_tag book, :book_image, :fit, 100, 100, fallback: "default-image.jpg" %>
              <br/>
              <%= book.title %>
          <% end %>
        </td>
        <td class="text-break"><%= book.author %></td>
        <td class="text-break"><%= book.isbn %></td>
        <td class="text-break"><%= book.body %></td>
      </tr>
    </tbody>
    <% end %>
  </table>
</div>

<!--全体-->
  </div>
</div>
</main>

app/views/book_articles/indexall.html.erb
<!--全体-->
<main>
<div class='container px-5 px-sm-0'>
  <div class='row'>

<!--ユーザーが投稿したbookのリスト-->
<div class='col-md-8 offset-md-1'>
  <h2>Books</h2>
  <table class='table table-hover table-inverse'>
    <thead>
      <tr>
        <th>User</th>
        <th>Book Title</th>
        <th>Autor</th>
        <th>Page</th>
        <th>Chapter</th>
        <th>Section</th>
        <th>Question</th>
        <th>Explanation</th>
        <th>article image</th>
      </tr>
    </thead>

<!--usersコントローラーのshowアクションで定義した@user_booksインスタンスからデータをよびだし -->
<!--booksコントローラーのindexアクションで定義した@booksインスタンスからデータをよびだし -->
    <% @bars.each do |bar| %>
    <tbody>
      <tr>
        <td class="text-break">
          <%= link_to user_path(bar.user_id) do %>
              <%= attachment_image_tag bar.user, :profile_image, :fit, 100, 100, fallback: "default-image.jpg" %>
              <br/>
              <%= bar.user.name %>
          <% end %>
        </td>
        <td class="text-break">
          <%= link_to book_path(bar.book_id) do %>
              <%= attachment_image_tag bar.book, :book_image, :fit, 100, 100, fallback: "default-image.jpg" %>
              <br/>
              <%= bar.book.title %>
          <% end %>
        </td>
        <td class="text-break"><%= bar.book.author %></td>
        <td class="text-break"><%= bar.page %></td>
        <td class="text-break"><%= bar.chapter %></td>
        <td class="text-break"><%= bar.section %></td>
        <td class="text-break"><%= bar.title %></td>
        <td class="text-break"><%= bar.body %></td>
        <td class="text-break">
          <% if bar.article_image.present? %>
            画像あり
          <% else %>
            画像なし
          <% end %>
        </td>
      </tr>
    </tbody>
    <% end %>
  </table>
</div>

<!--全体-->
  </div>
</div>
</main>

app/views/book_articles/new.html.erb
<!--Bootstrap部分  -->
<div class="container">
 <div class="row">
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

  <% if @bar.errors.any? %>
    <div id="error_explanation">
      <h2><%= @bar.errors.count %>errors prohibited this book from being saved:</h2>
      <ul>
      <% @bar.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h1>New Book Article</h1>


  <%= form_with(model:[@book, @bar], local: true) do |f| %>
    <div class="form-group">
      <%=f.label :book_id,"Book Title"%></br>
      <%= f.collection_select :book_id, @user_books, :id, :title, class:"form-control"%>
    </div>

    <div class="form-group">
      <%=f.label :page,"Page"%>
      <%= f.number_field :page,class:"form-control"%>
    </div>

    <div class="form-group">
      <%=f.label :chapter,"Chapter"%>
      <%= f.number_field :chapter,class:"form-control"%>
    </div>

    <div class="form-group">
      <%=f.label :section,"Section"%>
      <%= f.number_field :section,class:"form-control"%>
    </div>

    <div class="form-group">
      <%=f.label :title,"Question"%>
      <%= f.text_field :title,class:"form-control" %>
    </div>

    <div class="form-group">
      <%=f.label :body,"Explanation"%>
      <%= f.text_field :body,class:"form-control"%>
    </div>

    <div class="form-group">
      <%=f.label :article_image,"Image"%>
      <%= f.attachment_field :article_image, class:"form-control-file", id:"inputImage" %>
    </div>

    <div class="form-group">
      <%= f.submit 'Create Book',class: "btn btn-success" %>
    </div>
  <% end %>

  <%= link_to "Back", users_path %>

<!--Bootstrap部分  -->
  </div>
 </div>
</div>

app/views/book_articles/show.html.erb
<!--全体-->
<main>
  <p id="notice"><%= flash[:notice] %></p>
  <div class='container px-5 px-sm-0'>
    <div class='row'>

<!--右部分 -->
<!--ログインしているユーザーが投稿したbook　1冊だけ表示-->
      <div class='col-md-8 offset-md-1'>
        <h2>Book Article detail</h2>

        <table class='table table-hover table-inverse'>
          <thead>
            <tr>
              <th>User</th>
              <th>Book Title</th>
              <th>Page</th>
              <th>Chapter</th>
              <th>Section</th>
              <th>Question</th>
              <th>Explanation</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <tr>
              <td class="text-break">
                <%= link_to user_path(@bar.user_id) do %>
                    <%= attachment_image_tag @bar.user, :profile_image, :fit, 100, 100, fallback: "default-image.jpg" %>
                    <br/>
                    <%= @bar.user.name %>
                <% end %>
              </td>
              <td class="text-break">
                <%= link_to book_path(@bar.book_id) do %>
                    <%= attachment_image_tag @bar.book, :book_image, :fit, 100, 100, fallback: "default-image.jpg" %>
                    <br/>
                    <%= @bar.book.title %>
                <% end %>
              </td>
              <td class="text-break"><%= @bar.page %></td>
              <td class="text-break"><%= @bar.chapter %></td>
              <td class="text-break"><%= @bar.section %></td>
              <td class="text-break"><%= @bar.title %></td>
              <td class="text-break"><%= @bar.body %></td>

              <% if current_user.present? %>
              <% if @user.id == current_user.id %>
                <!--rails routesのPrefixを使う。アンダーバーの前。-->
                <!--classの後は、「：」。参照サイト：https://railsdoc.com/page/link_to-->
                <td><%= link_to 'Edit', edit_book_book_article_path(@bar.book.id, @bar.id),class: "btn btn-success"%></td>
                <td><%= link_to "Destroy", book_book_article_path(@bar.book.id, @bar.id), class: "btn btn-danger", method: :delete, "data-confirm" => "本当に消しますか？"%></td>
              <% end %>
              <% end %>
            </tr>
          </tbody>
        </table>

        <%= attachment_image_tag @bar, :article_image, :fit, 500, 500, fallback: "default-image.jpg" %>
        <br/>
        Article Image

        <div class='row'>
          <%= link_to 'Back Articles Index', book_book_articles_path(@bar.book.id) ,class: "btn btn-success" %>
        </div>

      </div>


<!--全体-->
    </div>
  </div>
</main>

app/views/book_images/destroy.html.erb
<h1>BookImages#destroy</h1>
<p>Find me in app/views/book_images/destroy.html.erb</p>

app/views/book_images/edit.html.erb
<h1>BookImages#edit</h1>
<p>Find me in app/views/book_images/edit.html.erb</p>

app/views/book_images/new.html.erb
    <h2>User info</h2>

      <%= form_with model:@bookimage,url:book_book_images_path,local:true do |f| %>


        <div class="form-group">
          <label for="inputImage">Image</label>
          <%= f.attachment_field :book_image_main, class:"form-control-file", id:"inputImage" %>
        </div>


        <div class="form-group">
          <%= f.submit "Update User" ,class:"btn btn-secondary" %>
        </div>

      <% end %>

app/views/book_images/update.html.erb
<h1>BookImages#update</h1>
<p>Find me in app/views/book_images/update.html.erb</p>

app/views/books/new.html.erb
<!--Bootstrap部分  -->
<div class="container">
 <div class="row">
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= @book.errors.count %>errors prohibited this book from being saved:</h2>
      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h1>New Book</h1>

  <%= form_with model: @book, local:true do |f| %>
    <div class="form-group">
      <%=f.label :title,"Title"%>
      <%= f.text_field :title,class:"form-control" %>
    </div>

    <div class="form-group">
      <%=f.label :author,"Author"%>
      <%= f.text_field :author,class:"form-control"%>
    </div>

    <div class="form-group">
      <%=f.label :isbn,"ISBN"%>
      <%= f.text_field :isbn,class:"form-control"%>
    </div>

    <div class="form-group">
      <%=f.label :book_image,"Image"%>
      <%= f.attachment_field :book_image, class:"form-control-file", id:"inputImage" %>
    </div>

    <div class="form-group">
      <%=f.label :body,"Comment"%>
      <%= f.text_area :body,class:"form-control"%>
    </div>

    <div class="form-group">
      <%= f.submit 'Create Book',class: "btn btn-success" %>
    </div>
  <% end %>

  <%= link_to "Back", users_path %>

<!--Bootstrap部分  -->
  </div>
 </div>
</div>

app/views/books/show.html.erb
<!--全体-->
<main>
  <p id="notice"><%= flash[:notice] %></p>
  <div class='container px-5 px-sm-0'>
    <div class='row'>

<!--右部分 -->
<!--ログインしているユーザーが投稿したbook　1冊だけ表示-->
      <div class='col-md-8 offset-md-1'>
        <h2>Book detail</h2>

        <table class='table table-hover table-inverse'>
          <thead>
            <tr>
              <th>User</th>
              <th>Title</th>
              <th>Autor</th>
              <th>ISBN</th>
              <th>Body</th>
              <th>Create date</th>
              <th>Update date</th>
              <th><%= 'Book&rsquo;s Articles Link'.html_safe %></th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <tr>
              <td class="text-break">
                <%= link_to user_path(@book.user_id) do %>
                    <%= attachment_image_tag @book.user, :profile_image, :fit, 100, 100, fallback: "default-image.jpg" %>
                    <br/>
                    <%= @book.user.name %>
                <% end %>
              </td>
              <td class="text-break">
                <%= link_to book_path(@book) do %>
                    <%= attachment_image_tag @book, :book_image, :fit, 100, 100, fallback: "default-image.jpg" %>
                    <br/>
                    <%= @book.title %>
                <% end %>
              </td>
              <td class="text-break"><%= @book.author %></td>
              <td class="text-break"><%= @book.isbn %></td>
              <td class="text-break"><%= @book.body %></td>
              <td class="text-break"><%= @book.created_at %></td>
              <td class="text-break"><%= @book.updated_at %></td>
              <td>
                <%= link_to 'Book&rsquo;s Articles Link'.html_safe,
                book_book_articles_path(@book.id), class: "btn btn-success"%>
              </td>

              <% if current_user.present? %>
              <% if @user.id == current_user.id %>
                <!--rails routesのPrefixを使う。アンダーバーの前。-->
                <!--classの後は、「：」。参照サイト：https://railsdoc.com/page/link_to-->
                <td><%= link_to 'Edit', edit_book_path(@book.id),class: "btn btn-success"%></td>
                <td><%= link_to "Destroy", book_path(@book.id), class: "btn btn-danger", method: :delete, "data-confirm" => "本当に消しますか？"%></td>
              <% end %>
              <% end %>
            </tr>
          </tbody>
        </table>
      </div>


<!--全体-->
    </div>
  </div>
</main>

app/views/homes/about.html.erb
 <!--https://pg-happy.jp/rails-applicationo-layout.html-->
<% @page_title = 'サイトの説明' %>

<main>
  <p id="notice"><%= flash[:notice] %></p>
  <div class='container'>
    <div class='row'>
      <h1 class="px-3 mx-auto">Welcome to
        <i class="fas fa-book"></i>
        <strong>Math Book Readers</strong>!
      </h1>
    </div>
  </div>
</main>

app/views/homes/top.html.erb
 <!--https://pg-happy.jp/rails-applicationo-layout.html-->
 <% @page_title = 'トップページ' %>

<main>
  <p id="notice"><%= flash[:notice] %></p>
  <div class="container">
    <div class="row">
      <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>
        <h1>welcome to
          <i class="fas fa-book"></i>
          <strong>Bookers</strong>!!
        </h1>
        <p>In
          <i class="fas fa-book"></i>
          <strong>Bookers</strong>,
        </p>
        <p>you can share and exchange your opinions , inpressions , and emotions</p>
        <p>about various books!</p>

        <% if user_signed_in? %>

        <% else %>
        <div class="btn-wrapper col-10 mx-auto">
          <div class="row">
            <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
          </div>
          <div class="row">
            <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<!--全体-->
<main>
   <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= @user.errors.count %>errors prohibited this user from being saved:</h2>
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
    <% end %>

  <p id="notice"><%= flash[:notice] %></p>
  <div class='container px-5 px-sm-0'>
    <div class='row'>

<!--ユーザーが投稿したbookのリスト-->
    <div class='col-md-8 offset-md-1'>
        <h2>User info</h2>

       <!--https://getbootstrap.jp/docs/4.5/content/tables/#always-responsive-->
          <table class='table table-hover table-inverse'>
            <tr>
              <%= attachment_image_tag @user, :profile_image, :fit, 60, 60, fallback: "default-image.jpg"  %>
            </tr>
            <tr>
              <th>name</th>
              <th class="text-break"><%= @user.name %></th>
            </tr>
            <tr>
              <th>introduction</th>
              <th class="text-break"><%= @user.introduction %></th>
            </tr>
          </table>

        <% if current_user.present? %>
        <% if @user.id == current_user.id %>
        <div class='row'>
          <%= link_to 'Edit User Info', edit_user_path(@user.id) ,class: "btn btn-success" %>
        </div>
        <% end %>
        <% end %>

        <div class='row'>
          <%= link_to 'Show User&rsquo;s Books'.html_safe, show_userbooks_path(@user.id) ,class: "btn btn-success" %>
        </div>

    </div>

<!--全体-->
    </div>
  </div>
</main>

app/views/users/userbookscreate.html.erb
<!--全体-->
<main>

  <div class='container px-5 px-sm-0'>
    <div class='row'>

<!--ユーザーが投稿したbookのリスト-->
    <div class='col-md-8 offset-md-1'>
      <h2>Which book ?  you wanna create article.</h2>
      <table class='table table-hover table-inverse'>
        <thead>
          <tr>
            <th>User</th>
            <th>Title</th>
            <th>Autor</th>
            <th>ISBN</th>
            <th>Body</th>
            <th>Select Link</th>
          </tr>
        </thead>

        <% @user_books.each do |book| %>
        <tbody>
          <tr>
            <td class="text-break">
              <%= link_to user_path(book.user_id) do %>
                  <%= attachment_image_tag book.user, :profile_image, :fit, 100, 100, fallback: "default-image.jpg" %>
                  <br/>
                  <%= book.user.name %>
              <% end %>
            </td>
            <td class="text-break">
              <%= link_to book_path(book) do %>
                  <%= attachment_image_tag book, :book_image, :fit, 100, 100, fallback: "default-image.jpg" %>
                  <br/>
                  <%= book.title %>
              <% end %>
            </td>
            <td class="text-break"><%= book.author %></td>
            <td class="text-break"><%= book.isbn %></td>
            <td class="text-break"><%= book.body %></td>
            <% if current_user.present? %>
              <% if @user.id == current_user.id %>
                <td><%= link_to 'Create New Article', new_book_book_article_path(book) %></td>
              <% end %>
            <% end %>

          </tr>
        </tbody>
        <% end %>
      </table>
    </div>

<!--全体-->
    </div>

    <div class='row'>
      <%= link_to 'Show User Info', user_path(@user.id), class: "btn btn-success" %>
    </div>
  </div>
</main>